### ISSUE TITLE
Is this final code?

### ISSUE THREAD

**Issue by hfarhidzadeh** [MrShininnnnn/HackNYU-2017-LCD#1]
Hi,

I have checked the code and seen the baseline CNN, but not U-net model or residual network.  Can you provide the final code?

**Comment by MrShininnnnn** [comment]
Hi friend,

Actually, I was responsible for the front-end development. The deep learning part was contributed by another folk [YichenGong](https://github.com/YichenGong). Please feel free to contact him.

**Comment by MrShininnnnn** [comment]
Closed due to no further issue.
